FROM node:20-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY sklep/package.json ./

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install app dependencies
RUN npm install

# Copy the current directory contents into the container at /app
COPY sklep/ .

# Expose port 4200 for the Angular app
EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]