version: '3'

networks:
    my_network: {}

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.angular
    container_name: angular-app-container
    ports:
      - "4200:4200"
    depends_on:
      - spring-app
    networks:
      - my_network