FROM maven:3.8.4-openjdk-17 as build
WORKDIR /app
COPY MVCsklep/demo /app
RUN mvn clean install -DskipTests

FROM openjdk:23-slim as run

# Set the working directory in the container
WORKDIR /app

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Make port 8080 available to the world outside this container
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]