# Use an official OpenJDK runtime as a parent image
FROM openjdk:23-slim

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container at /app
COPY MVCsklep/demo/target/demo-0.0.1-SNAPSHOT.jar /app

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the JAR file
CMD ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]